---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      vertx:
        applies-to: version-updates
        patterns:
        - "org.junit:*"
        - "org.junit.jupiter:*"
        update-types:
        - "minor"
        - "patch"
